### ISSUE TITLE
Error while deleting a pad

### ISSUE THREAD

**Issue by ldidry** [ether/ep_comments_page#182]
When I delete a pad (tested from API and from `adminpads` plugin), I have an error message in the logs:
```
[ERROR] console - PROHIBITED PROMISE BUG IN HOOK FUNCTION (plugin: ep_comments_page, function name: /home/luc/etherpad/node_modules/ep_comments_page/index:padRemove, hook: padRemove): The hook function provided a "thenable" (e.g., a Promise) which is prohibited because the hook expects to get the value synchronously.
```

It doesn’t prevent the pad to be deleted, though.

**Comment by JohnMcLear** [comment]
Try change ``padRemove`` to

```

exports.padRemove = async (hookName, context, cb) => {
  await Promise.all([
    commentManager.deleteCommentReplies(context.padID),
    commentManager.deleteComments(context.padID),
  ]);
  cb();
};

```

**Comment by ldidry** [comment]
It does not work:
```
[2021-01-05 16:05:34.826] [ERROR] console - PROHIBITED PROMISE BUG IN HOOK FUNCTION (plugin: ep_comments_page, function name: /home/luc/etherpad/node_modules/ep_comments_page/index:padRemove,
 hook: padRemove): The hook function provided a "thenable" (e.g., a Promise) which is prohibited because the hook expects to get the value synchronously.
[2021-01-05 16:05:34.827] [ERROR] console - DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_comments_page, function name: /home/luc/etherpad/node_modules/ep_comments_page/index:padRemove, hook
: padRemove): Attempt to resolve via callback but it already resolved via returned value. Ignoring this attempt to resolve.
[2021-01-05 16:05:34.829] [ERROR] console - (node:5038) UnhandledPromiseRejectionWarning: Error: DOUBLE SETTLE BUG IN HOOK FUNCTION (plugin: ep_comments_page, function name: /home/luc/etherpa
d/node_modules/ep_comments_page/index:padRemove, hook: padRemove): Attempt to resolve via callback but it already resolved via returned value. Ignoring this attempt to resolve.
    at settle (/home/luc/etherpad/src/static/js/pluginfw/hooks.js:129:27)
    at callback (/home/luc/etherpad/src/static/js/pluginfw/hooks.js:146:5)
    at Object.exports.padRemove [as hook_fn] (/home/luc/etherpad/node_modules/ep_comments_page/index.js:20:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-01-05 16:05:34.830] [ERROR] console - (node:5038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function wit
hout a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=stric
t` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2021-01-05 16:05:34.831] [ERROR] console - (node:5038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will
terminate the Node.js process with a non-zero exit code.
[2021-01-05 16:05:34.832] [ERROR] console - (node:5038) UnhandledPromiseRejectionWarning: apierror: padID does not exist
    at getPadSafe (/home/luc/etherpad/src/node/db/API.js:837:11)
    at async Object.exports.getLastEdited (/home/luc/etherpad/src/node/db/API.js:453:15)
[2021-01-05 16:05:34.833] [ERROR] console - (node:5038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function wit
hout a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=stric
t` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[2021-01-05 16:05:34.834] [ERROR] console - (node:5038) UnhandledPromiseRejectionWarning: apierror: padID does not exist
    at getPadSafe (/home/luc/etherpad/src/node/db/API.js:837:11)
    at async Object.exports.getLastEdited (/home/luc/etherpad/src/node/db/API.js:453:15)
```

And then I have a loop of the latest messages in the logs.

**Comment by JohnMcLear** [comment]
Try

```
exports.padRemove = async (hookName, context) => {
  await Promise.all([
    commentManager.deleteCommentReplies(context.padID),
    commentManager.deleteComments(context.padID),
  ]);
  return; 
};
``` 

??

**Comment by ldidry** [comment]
Same loop of messages in the logs.

**Comment by JohnMcLear** [comment]
Ugh okay will take a look into it buddy :)

**Comment by JohnMcLear** [comment]
Fixed in https://github.com/ether/ep_comments_page/commit/a6ebecdfb73ddf15dd05b13a2825ccd441353488
