### ISSUE TITLE
src/bin/run.sh fails after installing ep_comments_page

### ISSUE THREAD

**Issue by riedelcastro** [ether/ep_comments_page#234]
Hi,

I have installed etherpad lite as per the "Manual Installation" section on its README, and ep_comments_page via `npm install ep_comments_page`. We I run `src/bin/run.sh`, the script breaks and exists with the issue below. I am running npm version 7.11.2 on Mac OS.

What could I be doing wrong? 

```
[2022-03-24 01:18:20.938] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /Users/riedelcastro/projects/etherpad-lite
[2022-03-24 01:18:21.052] [INFO] settings - settings loaded from: /Users/riedelcastro/projects/etherpad-lite/settings.json
[2022-03-24 01:18:21.053] [INFO] settings - No credentials file found in /Users/riedelcastro/projects/etherpad-lite/credentials.json. Ignoring.
[2022-03-24 01:18:21.054] [INFO] settings - Using skin "colibris" in dir: /Users/riedelcastro/projects/etherpad-lite/src/static/skins/colibris
[2022-03-24 01:18:21.054] [INFO] settings - Session key loaded from: /Users/riedelcastro/projects/etherpad-lite/SESSIONKEY.txt
[2022-03-24 01:18:21.054] [WARN] settings - DirtyDB is used. This is not recommended for production. File location: /Users/riedelcastro/projects/etherpad-lite/var/dirty.db
[2022-03-24 01:18:21.055] [INFO] settings - Random string used for versioning assets: dedb00ed
[2022-03-24 01:18:21.927] [INFO] server - Starting Etherpad...
[2022-03-24 01:18:22.113] [INFO] plugins - Running npm to get a list of installed plugins...
[2022-03-24 01:18:22.649] [INFO] plugins - npm --version: 6.14.15
[2022-03-24 01:18:34.071] [ERROR] runCmd|npm - npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
[2022-03-24 01:18:38.975] [ERROR] runCmd|npm - npm ERR! missing: @typescript-eslint/eslint-plugin@5.16.0, required by etherpad-lite
[2022-03-24 01:18:38.975] [ERROR] runCmd|npm - npm ERR! missing: @typescript-eslint/parser@5.16.0, required by etherpad-lite
[2022-03-24 01:18:38.975] [ERROR] runCmd|npm - npm ERR! missing: eslint@7.32.0, required by etherpad-lite
[2022-03-24 01:18:38.975] [ERROR] runCmd|npm - npm ERR! missing: eslint-config-etherpad@2.1.0, required by etherpad-lite
[2022-03-24 01:18:38.975] [ERROR] runCmd|npm - npm ERR! missing: eslint-import-resolver-typescript@2.7.0, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-cypress@2.12.1, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-eslint-comments@3.2.0, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-import@2.25.4, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-mocha@9.0.0, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-node@11.1.0, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-prefer-arrow@1.2.3, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-promise@5.2.0, required by etherpad-lite
[2022-03-24 01:18:38.976] [ERROR] runCmd|npm - npm ERR! missing: eslint-plugin-you-dont-need-lodash-underscore@6.12.0, required by etherpad-lite
[2022-03-24 01:18:38.991] [ERROR] runCmd|npm - npm ERR! missing: etherpad-cli-client@0.1.13, required by etherpad-lite
[2022-03-24 01:18:38.991] [ERROR] runCmd|npm - npm ERR! missing: mocha@9.2.2, required by etherpad-lite
[2022-03-24 01:18:38.991] [ERROR] runCmd|npm - npm ERR! missing: mocha-froth@0.2.10, required by etherpad-lite
[2022-03-24 01:18:38.991] [ERROR] runCmd|npm - npm ERR! missing: nodeify@1.0.1, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: openapi-schema-validation@0.4.2, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: selenium-webdriver@4.1.1, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: set-cookie-parser@2.4.8, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: sinon@11.1.2, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: split-grid@1.0.11, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: supertest@6.2.2, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: typescript@4.6.2, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! missing: ep_comments_page@1.0.0, required by etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! extraneous: @typescript-eslint/eslint-plugin@5.16.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/@typescript-eslint/eslint-plugin
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! extraneous: @typescript-eslint/parser@5.16.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/@typescript-eslint/parser
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! extraneous: ep_etherpad-lite@1.8.17 /Users/riedelcastro/projects/etherpad-lite/node_modules/ep_etherpad-lite
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! extraneous: eslint@7.32.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-config-etherpad@2.1.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-config-etherpad
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-import-resolver-typescript@2.7.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-import-resolver-typescript
[2022-03-24 01:18:38.992] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-cypress@2.12.1 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-cypress
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-eslint-comments@3.2.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-eslint-comments
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-import@2.25.4 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-import
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-mocha@9.0.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-mocha
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-node@11.1.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-node
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-prefer-arrow@1.2.3 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-prefer-arrow
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-promise@5.2.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-promise
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: eslint-plugin-you-dont-need-lodash-underscore@6.12.0 /Users/riedelcastro/projects/etherpad-lite/node_modules/eslint-plugin-you-dont-need-lodash-underscore
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: etherpad-cli-client@0.1.13 /Users/riedelcastro/projects/etherpad-lite/node_modules/etherpad-cli-client
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: mocha@9.2.2 /Users/riedelcastro/projects/etherpad-lite/node_modules/mocha
[2022-03-24 01:18:38.993] [ERROR] runCmd|npm - npm ERR! extraneous: mocha-froth@0.2.10 /Users/riedelcastro/projects/etherpad-lite/node_modules/mocha-froth
[2022-03-24 01:18:39.041] [ERROR] runCmd|npm - npm ERR! extraneous: nodeify@1.0.1 /Users/riedelcastro/projects/etherpad-lite/node_modules/nodeify
[2022-03-24 01:18:39.042] [ERROR] runCmd|npm - npm ERR! extraneous: openapi-schema-validation@0.4.2 /Users/riedelcastro/projects/etherpad-lite/node_modules/openapi-schema-validation
[2022-03-24 01:18:39.044] [ERROR] runCmd|npm - npm ERR! extraneous: selenium-webdriver@4.1.1 /Users/riedelcastro/projects/etherpad-lite/node_modules/selenium-webdriver
[2022-03-24 01:18:39.044] [ERROR] runCmd|npm - npm ERR! extraneous: set-cookie-parser@2.4.8 /Users/riedelcastro/projects/etherpad-lite/node_modules/set-cookie-parser
[2022-03-24 01:18:39.044] [ERROR] runCmd|npm - npm ERR! extraneous: sinon@11.1.2 /Users/riedelcastro/projects/etherpad-lite/node_modules/sinon
[2022-03-24 01:18:39.044] [ERROR] runCmd|npm - npm ERR! extraneous: split-grid@1.0.11 /Users/riedelcastro/projects/etherpad-lite/node_modules/split-grid
[2022-03-24 01:18:39.044] [ERROR] runCmd|npm - npm ERR! extraneous: supertest@6.2.2 /Users/riedelcastro/projects/etherpad-lite/node_modules/supertest
[2022-03-24 01:18:39.045] [ERROR] runCmd|npm - npm ERR! extraneous: typescript@4.6.2 /Users/riedelcastro/projects/etherpad-lite/node_modules/typescript
[2022-03-24 01:18:39.045] [ERROR] runCmd|npm - npm ERR! missing: cheerio@0.22.0, required by ep_comments_page@1.0.0
[2022-03-24 01:18:39.045] [ERROR] runCmd|npm - npm ERR! missing: formidable@2.0.1, required by ep_comments_page@1.0.0
[2022-03-24 01:18:39.045] [ERROR] runCmd|npm - npm ERR! missing: underscore@1.13.2, required by ep_comments_page@1.0.0
[2022-03-24 01:18:39.045] [ERROR] runCmd|npm - npm ERR! missing: css-select@1.2.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.046] [ERROR] runCmd|npm - npm ERR! missing: dom-serializer@0.1.1, required by cheerio@0.22.0
[2022-03-24 01:18:39.046] [ERROR] runCmd|npm - npm ERR! missing: entities@1.1.2, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: htmlparser2@3.10.1, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.assignin@4.2.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.bind@4.2.1, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.defaults@4.2.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.filter@4.6.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.flatten@4.4.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.foreach@4.5.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.map@4.6.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.047] [ERROR] runCmd|npm - npm ERR! missing: lodash.merge@4.6.2, required by cheerio@0.22.0
[2022-03-24 01:18:39.048] [ERROR] runCmd|npm - npm ERR! missing: lodash.pick@4.4.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.048] [ERROR] runCmd|npm - npm ERR! missing: lodash.reduce@4.6.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.049] [ERROR] runCmd|npm - npm ERR! missing: lodash.reject@4.6.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.049] [ERROR] runCmd|npm - npm ERR! missing: lodash.some@4.6.0, required by cheerio@0.22.0
[2022-03-24 01:18:39.049] [ERROR] runCmd|npm - npm ERR! missing: boolbase@1.0.0, required by css-select@1.2.0
[2022-03-24 01:18:39.049] [ERROR] runCmd|npm - npm ERR! missing: css-what@2.1.3, required by css-select@1.2.0
[2022-03-24 01:18:39.049] [ERROR] runCmd|npm - npm ERR! missing: domutils@1.5.1, required by css-select@1.2.0
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: nth-check@1.0.2, required by css-select@1.2.0
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: dom-serializer@0.1.1, required by domutils@1.5.1
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: domelementtype@1.3.1, required by domutils@1.5.1
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: boolbase@1.0.0, required by nth-check@1.0.2
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: domelementtype@1.3.1, required by dom-serializer@0.1.1
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: entities@1.1.2, required by dom-serializer@0.1.1
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: domelementtype@1.3.1, required by htmlparser2@3.10.1
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: domhandler@2.4.2, required by htmlparser2@3.10.1
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: domutils@1.5.1, required by htmlparser2@3.10.1
[2022-03-24 01:18:39.050] [ERROR] runCmd|npm - npm ERR! missing: entities@1.1.2, required by htmlparser2@3.10.1
[2022-03-24 01:18:39.051] [ERROR] runCmd|npm - npm ERR! missing: inherits@2.0.4, required by htmlparser2@3.10.1
[2022-03-24 01:18:39.051] [ERROR] runCmd|npm - npm ERR! missing: readable-stream@3.6.0, required by htmlparser2@3.10.1
[2022-03-24 01:18:39.051] [ERROR] runCmd|npm - npm ERR! missing: domelementtype@1.3.1, required by domhandler@2.4.2
[2022-03-24 01:18:39.051] [ERROR] runCmd|npm - npm ERR! missing: inherits@2.0.4, required by readable-stream@3.6.0
[2022-03-24 01:18:39.051] [ERROR] runCmd|npm - npm ERR! missing: string_decoder@1.3.0, required by readable-stream@3.6.0
[2022-03-24 01:18:39.052] [ERROR] runCmd|npm - npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@3.6.0
[2022-03-24 01:18:39.053] [ERROR] runCmd|npm - npm ERR! missing: safe-buffer@5.2.1, required by string_decoder@1.3.0
[2022-03-24 01:18:39.053] [ERROR] runCmd|npm - npm ERR! missing: dezalgo@1.0.3, required by formidable@2.0.1
[2022-03-24 01:18:39.054] [ERROR] runCmd|npm - npm ERR! missing: hexoid@1.0.0, required by formidable@2.0.1
[2022-03-24 01:18:39.054] [ERROR] runCmd|npm - npm ERR! missing: once@1.4.0, required by formidable@2.0.1
[2022-03-24 01:18:39.054] [ERROR] runCmd|npm - npm ERR! missing: qs@6.9.3, required by formidable@2.0.1
[2022-03-24 01:18:39.054] [ERROR] runCmd|npm - npm ERR! missing: asap@2.0.6, required by dezalgo@1.0.3
[2022-03-24 01:18:39.054] [ERROR] runCmd|npm - npm ERR! missing: wrappy@1.0.2, required by dezalgo@1.0.3
[2022-03-24 01:18:39.054] [ERROR] runCmd|npm - npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
[2022-03-24 01:18:39.105] [ERROR] server - Error occurred while starting Etherpad
[2022-03-24 01:18:39.106] [ERROR] server - Metrics at time of fatal error:
{
  "httpStartTime": 0,
  "memoryUsage": 47509504,
  "memoryUsageHeap": 14808184,
  "ueberdb_lockAwaits": 0,
  "ueberdb_lockAcquires": 0,
  "ueberdb_lockReleases": 0,
  "ueberdb_reads": 0,
  "ueberdb_readsFailed": 0,
  "ueberdb_readsFinished": 0,
  "ueberdb_readsFromCache": 0,
  "ueberdb_readsFromDb": 0,
  "ueberdb_readsFromDbFailed": 0,
  "ueberdb_readsFromDbFinished": 0,
  "ueberdb_writes": 0,
  "ueberdb_writesFailed": 0,
  "ueberdb_writesFinished": 0,
  "ueberdb_writesObsoleted": 0,
  "ueberdb_writesToDb": 0,
  "ueberdb_writesToDbFailed": 0,
  "ueberdb_writesToDbFinished": 0,
  "ueberdb_writesToDbRetried": 0
}
[2022-03-24 01:18:39.106] [ERROR] server - Error: Command exited with code 1: npm ls --long --json --depth=0 --no-production
    at exports (/Users/riedelcastro/projects/etherpad-lite/src/node/utils/run_cmd.js:119:25)
    at Object.exports.getPackages (/Users/riedelcastro/projects/etherpad-lite/src/static/js/pluginfw/plugins.js:112:48)
    at Object.exports.update (/Users/riedelcastro/projects/etherpad-lite/src/static/js/pluginfw/plugins.js:86:34)
    at Object.exports.start (/Users/riedelcastro/projects/etherpad-lite/src/node/server.js:143:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-03-24 01:18:39.106] [INFO] server - Exiting...
[2022-03-24 01:18:39.106] [INFO] server - Waiting for Node.js to exit...
```

**Comment by rhansen** [comment]
With npm v7 and later you must pass `--no-save --legacy-peer-deps` when installing plugins:

```shell
rm package*.json # Clean up after the failed plugin installation.
cd /path/to/etherpad-lite
npm install --no-save --legacy-peer-deps ep_comments_page
```

**Comment by riedelcastro** [comment]
Amazing, that worked right away! Thanks so much for the quick reply.
